export const iranStates = {
  iran: {
    id: 0,
    name: 'ایران',
    enName: 'iran',
    latitude: '54.240102',
    longitude: '32.9061634',
    zoom: 5,
  },
  tehran: {
    id: 1,
    name: 'تهران',
    enName: 'tehran',
    latitude: '51.385',
    longitude: '35.688',
    zoom: 8,
  },
  ardabil: {
    id: 2,
    name: 'اردبیل',
    enName: 'ardabil',
    latitude: '48.12',
    longitude: '38.65',
    zoom: 8,
  },
  esfahan: {
    id: 3,
    name: 'اصفهان',
    enName: 'esfahan',
    latitude: '51.69',
    longitude: '32.70',
    zoom: 8,
  },
  alborz: {
    id: 4,
    name: 'البرز',
    enName: 'alborz',
    latitude: '50.87',
    longitude: '36.02',
    zoom: 8,
  },
  ilam: {
    id: 5,
    name: 'ایلام',
    enName: 'ilam',
    latitude: '46.92',
    longitude: '32.99',
    zoom: 8,
  },
  azarbayeJanSharqi: {
    id: 6,
    name: 'آذربایجان شرقی',
    enName: 'east azarbaijan',
    latitude: '46.28',
    longitude: '38.07',
    zoom: 8,
  },
  azarbayeJanQarbi: {
    id: 7,
    name: 'آذربایجان غربی',
    enName: 'west azarbaijan',
    latitude: '45.04',
    longitude: '37.55',
    zoom: 8,
  },
  bushehr: {
    id: 8,
    name: 'بوشهر',
    enName: 'bushehr',
    latitude: '51.39',
    longitude: '28.51',
    zoom: 8,
  },
  chaharmahalVaBakhtiary: {
    id: 9,
    name: 'چهارمحال و بختیاری',
    enName: 'chaharmahal va bakhtiary',
    latitude: '50.43',
    longitude: '31.89',
    zoom: 8,
  },
  khorasanJonobi: {
    id: 10,
    name: 'خراسان جنوبی',
    enName: 'khorasan jonobi',
    latitude: '59.23',
    longitude: '32.89',
    zoom: 8,
  },
  khorasanRazavi: {
    id: 11,
    name: 'خراسان رضوی',
    enName: 'khorasan razavi',
    latitude: '58.96',
    longitude: '35.91',
    zoom: 8,
  },
  khorasanShomali: {
    id: 12,
    name: 'خراسان شمالی',
    enName: 'khorasan shomali',
    latitude: '57.37',
    longitude: '37.57',
    zoom: 8,
  },
  khozestan: {
    id: 13,
    name: 'خوزستان',
    enName: 'khozestan',
    latitude: '49.07',
    longitude: '31.27',
    zoom: 8,
  },
  zanjan: {
    id: 14,
    name: 'زنجان',
    enName: 'zanjan',
    latitude: '48.31',
    longitude: '36.58',
    zoom: 8,
  },
  semnan: {
    id: 15,
    name: 'سمنان',
    enName: 'semnan',
    latitude: '54.58',
    longitude: '35.89',
    zoom: 8,
  },
  sistanBaluchestan: {
    id: 16,
    name: 'سیستان و بلوچستان',
    enName: 'sistan va balochestan',
    latitude: '60.68',
    longitude: '27.23',
    zoom: 8,
  },
  fars: {
    id: 17,
    name: 'فارس',
    enName: 'fars',
    latitude: '52.51',
    longitude: '29.63',
    zoom: 8,
  },
  qazvin: {
    id: 18,
    name: 'قزوین',
    enName: 'qazvin',
    latitude: '49.79',
    longitude: '36.22',
    zoom: 8,
  },
  qom: {
    id: 19,
    name: 'قم',
    enName: 'qum',
    latitude: '51.07',
    longitude: '34.71',
    zoom: 8,
  },
  kordestan: {
    id: 20,
    name: 'کردستان',
    enName: 'kordestan',
    latitude: '46.89',
    longitude: '35.73',
    zoom: 8,
  },
  kerman: {
    id: 21,
    name: 'کرمان',
    enName: 'kerman',
    latitude: '57.06',
    longitude: '30.28',
    zoom: 8,
  },
  kermanshah: {
    id: 22,
    name: 'کرمانشاه',
    enName: 'kermanshah',
    latitude: '46.79',
    longitude: '34.52',
    zoom: 8,
  },
  kohghiloyeVaBoyerahmad: {
    id: 23,
    name: 'کهگیلویه و بویر احمد',
    enName: 'kohghiloye va boyerahmad',
    latitude: '50.84',
    longitude: '30.48',
    zoom: 8,
  },
  gholestan: {
    id: 24,
    name: 'گلستان',
    enName: 'gholestan',
    latitude: '55.21',
    longitude: '37.45',
    zoom: 8,
  },
  gilan: {
    id: 25,
    name: 'گیلان',
    enName: 'gilan',
    latitude: '49.59',
    longitude: '37.51',
    zoom: 8,
  },
  lorestan: {
    id: 26,
    name: 'لرستان',
    enName: 'lorestan',
    latitude: '48.41',
    longitude: '33.52',
    zoom: 8,
  },
  mazandaran: {
    id: 27,
    name: 'مازندران',
    enName: 'mazandaran',
    latitude: '52.32',
    longitude: '36.45',
    zoom: 8,
  },
  markazi: {
    id: 28,
    name: 'مرکزی',
    enName: 'markazi',
    latitude: '49.99',
    longitude: '34.46',
    zoom: 8,
  },
  hormozgan: {
    id: 29,
    name: 'هرمزگان',
    enName: 'hormozgan',
    latitude: '56.23',
    longitude: '27.19',
    zoom: 8,
  },
  hamedan: {
    id: 30,
    name: 'همدان',
    enName: 'hamedan',
    latitude: '48.64',
    longitude: '34.91',
    zoom: 8,
  },
  yazd: {
    id: 31,
    name: 'یزد',
    enName: 'yazd',
    latitude: '54.86',
    longitude: '31.48',
    zoom: 8,
  },
};
